export const THEMES = [
  {
    id: 'void',
    name: 'VOID',
    desc: 'Default dark purple',
    preview: '#0e0e14',
    vars: {
      '--bg-deeper':    '#080810',
      '--bg-base':      '#0e0e14',
      '--bg-header':    '#0c0c14',
      '--bg-panel':     '#16161f',
      '--bg-track':     '#1c1c28',
      '--bg-control':   '#0e0e1c',
      '--bg-hover':     '#141428',
      '--border-subtle':'#1a1a28',
      '--border':       '#252535',
      '--text-primary': '#e0e0ee',
      '--text-muted':   '#666680',
    },
  },
  {
    id: 'crimson',
    name: 'CRIMSON',
    desc: 'Blood-red night',
    preview: '#140a0a',
    vars: {
      '--bg-deeper':    '#0a0404',
      '--bg-base':      '#140a0a',
      '--bg-header':    '#100808',
      '--bg-panel':     '#1c0f0f',
      '--bg-track':     '#221515',
      '--bg-control':   '#140c0c',
      '--bg-hover':     '#1c1010',
      '--border-subtle':'#2a1414',
      '--border':       '#3a1a1a',
      '--text-primary': '#eee0e0',
      '--text-muted':   '#805050',
    },
  },
  {
    id: 'abyss',
    name: 'ABYSS',
    desc: 'Deep ocean blue',
    preview: '#080f14',
    vars: {
      '--bg-deeper':    '#040a10',
      '--bg-base':      '#080f14',
      '--bg-header':    '#061018',
      '--bg-panel':     '#0d1820',
      '--bg-track':     '#111f2a',
      '--bg-control':   '#081318',
      '--bg-hover':     '#0e1a24',
      '--border-subtle':'#102030',
      '--border':       '#1a3040',
      '--text-primary': '#d0e8f0',
      '--text-muted':   '#3a6075',
    },
  },
  {
    id: 'matrix',
    name: 'MATRIX',
    desc: 'Terminal green',
    preview: '#040f08',
    vars: {
      '--bg-deeper':    '#020a04',
      '--bg-base':      '#040f08',
      '--bg-header':    '#041008',
      '--bg-panel':     '#081610',
      '--bg-track':     '#0c1e14',
      '--bg-control':   '#061008',
      '--bg-hover':     '#0a1a0e',
      '--border-subtle':'#0c2010',
      '--border':       '#143020',
      '--text-primary': '#c8f0d4',
      '--text-muted':   '#2a6040',
    },
  },
  {
    id: 'synthwave',
    name: 'SYNTHWAVE',
    desc: 'Neon violet dusk',
    preview: '#110e18',
    vars: {
      '--bg-deeper':    '#080610',
      '--bg-base':      '#110e18',
      '--bg-header':    '#0e0c18',
      '--bg-panel':     '#18122a',
      '--bg-track':     '#1e1630',
      '--bg-control':   '#100e1c',
      '--bg-hover':     '#181228',
      '--border-subtle':'#201840',
      '--border':       '#2e1a50',
      '--text-primary': '#e8d8ff',
      '--text-muted':   '#6040a0',
    },
  },
  {
    id: 'white',
    name: 'WHITE',
    desc: 'Clean light studio',
    preview: '#f0f0f8',
    vars: {
      '--bg-deeper':    '#dcdce8',
      '--bg-base':      '#f0f0f8',
      '--bg-header':    '#e4e4f0',
      '--bg-panel':     '#e8e8f4',
      '--bg-track':     '#dedee8',
      '--bg-control':   '#f4f4fc',
      '--bg-hover':     '#d4d4e4',
      '--border-subtle':'#c4c4d8',
      '--border':       '#a0a0b8',
      '--text-primary': '#1a1a2a',
      '--text-muted':   '#606080',
    },
  },
]

export function applyTheme(themeId) {
  const theme = THEMES.find(t => t.id === themeId) ?? THEMES[0]
  const root = document.documentElement
  for (const [prop, val] of Object.entries(theme.vars)) {
    root.style.setProperty(prop, val)
  }
}
