export const THEMES = [
  {
    id: 'white',
    name: 'WHITE',
    desc: 'Clean light studio',
    preview: '#f0f0f8',
    vars: {
      '--bg-deeper':    '#d4d4e4',
      '--bg-base':      '#f0f0f8',
      '--bg-header':    '#e4e4f2',
      '--bg-panel':     '#eaeaf6',
      '--bg-track':     '#dddde8',
      '--bg-control':   '#f6f6ff',
      '--bg-hover':     '#ccccde',
      '--border-subtle':'#bcbcd0',
      '--border':       '#9494b0',
      '--text-primary': '#18182a',
      '--text-muted':   '#58587a',
    },
  },
  {
    id: 'arctic',
    name: 'ARCTIC',
    desc: 'Icy cool blue-white',
    preview: '#eef6ff',
    vars: {
      '--bg-deeper':    '#d4e4f4',
      '--bg-base':      '#eef6ff',
      '--bg-header':    '#e2f0ff',
      '--bg-panel':     '#e8f2ff',
      '--bg-track':     '#daeaf8',
      '--bg-control':   '#f4f8ff',
      '--bg-hover':     '#ccddf0',
      '--border-subtle':'#b0ccdf',
      '--border':       '#86aece',
      '--text-primary': '#0a1a28',
      '--text-muted':   '#3d6080',
    },
  },
  {
    id: 'void',
    name: 'VOID',
    desc: 'Dark purple cosmos',
    preview: '#0e0e14',
    vars: {
      '--bg-deeper':    '#080810',
      '--bg-base':      '#0e0e14',
      '--bg-header':    '#0c0c14',
      '--bg-panel':     '#16161f',
      '--bg-track':     '#1c1c28',
      '--bg-control':   '#0e0e1c',
      '--bg-hover':     '#141428',
      '--border-subtle':'#1a1a28',
      '--border':       '#252535',
      '--text-primary': '#e0e0ee',
      '--text-muted':   '#666680',
    },
  },
  {
    id: 'carbon',
    name: 'CARBON',
    desc: 'Pure dark neutral',
    preview: '#111111',
    vars: {
      '--bg-deeper':    '#080808',
      '--bg-base':      '#111111',
      '--bg-header':    '#0d0d0d',
      '--bg-panel':     '#1a1a1a',
      '--bg-track':     '#202020',
      '--bg-control':   '#131313',
      '--bg-hover':     '#1a1a1a',
      '--border-subtle':'#252525',
      '--border':       '#333333',
      '--text-primary': '#e4e4e4',
      '--text-muted':   '#646464',
    },
  },
  {
    id: 'crimson',
    name: 'CRIMSON',
    desc: 'Blood-red night',
    preview: '#140a0a',
    vars: {
      '--bg-deeper':    '#0a0404',
      '--bg-base':      '#140a0a',
      '--bg-header':    '#100808',
      '--bg-panel':     '#1c0f0f',
      '--bg-track':     '#221515',
      '--bg-control':   '#140c0c',
      '--bg-hover':     '#1c1010',
      '--border-subtle':'#2a1414',
      '--border':       '#3a1a1a',
      '--text-primary': '#eee0e0',
      '--text-muted':   '#805050',
    },
  },
  {
    id: 'abyss',
    name: 'ABYSS',
    desc: 'Deep ocean blue',
    preview: '#080f14',
    vars: {
      '--bg-deeper':    '#040a10',
      '--bg-base':      '#080f14',
      '--bg-header':    '#061018',
      '--bg-panel':     '#0d1820',
      '--bg-track':     '#111f2a',
      '--bg-control':   '#081318',
      '--bg-hover':     '#0e1a24',
      '--border-subtle':'#102030',
      '--border':       '#1a3040',
      '--text-primary': '#d0e8f0',
      '--text-muted':   '#3a6075',
    },
  },
  {
    id: 'matrix',
    name: 'MATRIX',
    desc: 'Terminal green',
    preview: '#040f08',
    vars: {
      '--bg-deeper':    '#020a04',
      '--bg-base':      '#040f08',
      '--bg-header':    '#041008',
      '--bg-panel':     '#081610',
      '--bg-track':     '#0c1e14',
      '--bg-control':   '#061008',
      '--bg-hover':     '#0a1a0e',
      '--border-subtle':'#0c2010',
      '--border':       '#143020',
      '--text-primary': '#c8f0d4',
      '--text-muted':   '#2a6040',
    },
  },
  {
    id: 'synthwave',
    name: 'SYNTHWAVE',
    desc: 'Neon violet dusk',
    preview: '#110e18',
    vars: {
      '--bg-deeper':    '#080610',
      '--bg-base':      '#110e18',
      '--bg-header':    '#0e0c18',
      '--bg-panel':     '#18122a',
      '--bg-track':     '#1e1630',
      '--bg-control':   '#100e1c',
      '--bg-hover':     '#181228',
      '--border-subtle':'#201840',
      '--border':       '#2e1a50',
      '--text-primary': '#e8d8ff',
      '--text-muted':   '#6040a0',
    },
  },
  {
    id: 'sunset',
    name: 'SUNSET',
    desc: 'Warm amber night',
    preview: '#1a1008',
    vars: {
      '--bg-deeper':    '#100800',
      '--bg-base':      '#1a1008',
      '--bg-header':    '#160e06',
      '--bg-panel':     '#221508',
      '--bg-track':     '#2a1c0a',
      '--bg-control':   '#1a1006',
      '--bg-hover':     '#221408',
      '--border-subtle':'#341c08',
      '--border':       '#4a2810',
      '--text-primary': '#ffd8a8',
      '--text-muted':   '#9a6030',
    },
  },
  {
    id: 'sakura',
    name: 'SAKURA',
    desc: 'Dark rose blossom',
    preview: '#180c12',
    vars: {
      '--bg-deeper':    '#0e0608',
      '--bg-base':      '#180c12',
      '--bg-header':    '#14080e',
      '--bg-panel':     '#201018',
      '--bg-track':     '#281520',
      '--bg-control':   '#160a10',
      '--bg-hover':     '#20101a',
      '--border-subtle':'#301828',
      '--border':       '#482038',
      '--text-primary': '#ffd0e4',
      '--text-muted':   '#904060',
    },
  },
]

export function applyTheme(themeId) {
  const theme = THEMES.find(t => t.id === themeId) ?? THEMES[0]
  const root = document.documentElement
  for (const [prop, val] of Object.entries(theme.vars)) {
    root.style.setProperty(prop, val)
  }
}
